Repository acmestack/envcd, pull requests merged in 2022-08, with the labels that each got.

#84 [type:feat] build context
  internal/core/openapi/auth.go
  internal/util/contextutil.go
Labels: enhancement

#86 [type: refactor] refactor envcd context build.
  internal/core/openapi/auth.go
  internal/core/openapi/context.go
Labels: enhancement

#83 [type:feat] password generate strategy submit
  internal/util/passwordutil.go
  internal/util/passwordutil_test.go
Labels: enhancement, good first issue

#88 [type: feat] add file license check
  .github/workflows/license.yaml
  .licenserc.json
  internal/core/exchanger/etcd/etcd_test.go
Labels: enhancement

#90 [type: refactor] refactor password logic.
  internal/core/openapi/password.go
  internal/core/openapi/password_test.go
Labels: enhancement

#93 update licence template
  .licenserc.json
  NOTICE
  cmd/envcd/main.go
  db/envcd.sql
  envcd.svg
  internal/core/configuration/configuration.go
  internal/core/exchanger/etcd/etcd.go
  internal/core/exchanger/etcd/etcd_test.go
  internal/core/exchanger/exchange.go
  internal/core/exchanger/exchange_test.go
  internal/core/openapi/application.go
  internal/core/openapi/context.go
  internal/core/openapi/dictionary.go
  internal/core/openapi/openapi.go
  internal/core/openapi/password.go
  internal/core/openapi/password_test.go
  internal/core/openapi/user.go
  internal/core/plugin/chain.go
  internal/core/plugin/chain_test.go
  internal/core/plugin/logging/logging.go
  internal/core/plugin/logging/logging_test.go
  internal/core/plugin/permission/permission.go
  internal/core/storage/dao/application.go
  internal/core/storage/dao/dao.go
  internal/core/storage/dao/dictionary.go
  internal/core/storage/dao/logging.go
  internal/core/storage/dao/permission.go
  internal/core/storage/dao/user.go
  internal/core/storage/storage.go
  internal/core/storage/xml/application_mapper.xml
  internal/core/storage/xml/dictionary_mapper.xml
  internal/core/storage/xml/logging_mapper.xml
  internal/core/storage/xml/permission_mapper.xml
  internal/core/storage/xml/user_mapper.xml
  internal/envcd/envcd.go
  internal/pkg/config/config.go
  internal/pkg/config/config_test.go
  internal/pkg/config/conn_metadata.go
  internal/pkg/config/conn_metadata_test.go
  internal/pkg/constants/constants.go
  internal/pkg/context/context.go
  internal/pkg/entity/application.go
  internal/pkg/entity/dictionary.go
  internal/pkg/entity/logging.go
  internal/pkg/entity/permission.go
  internal/pkg/entity/user.go
  internal/pkg/executor/chain.go
  internal/pkg/executor/executor.go
  internal/pkg/plugin/plugin.go
  pkg/entity/data/envcd_data.go
  pkg/entity/data/envcd_data_test.go
  pkg/entity/data/envcd_result.go
  pkg/entity/data/envcd_result_test.go
  pkg/entity/scope_space.go
  pkg/entity/user.go
  test/errorsx_test.go
Labels: enhancement, wontfix

#91 [type: feat] create user api.
  go.mod
  go.sum
  internal/core/openapi/password.go
  internal/core/openapi/user.go
Labels: enhancement

#95 [type: refactor] refactor context & envcd result
  internal/core/openapi/application.go
  internal/core/openapi/context.go
  internal/core/openapi/dictionary.go
  internal/core/openapi/openapi.go
  internal/core/openapi/user.go
  internal/core/plugin/chain.go
  internal/core/plugin/chain_test.go
  internal/core/plugin/logging/logging.go
  internal/core/plugin/logging/logging_test.go
  internal/core/plugin/permission/permission.go
  internal/pkg/context/context.go
  internal/pkg/executor/chain.go
  internal/pkg/executor/executor.go
  pkg/entity/result/envcd_result.go
  pkg/entity/result/envcd_result_test.go
Labels: enhancement

#96 [type: refactor] refactor build context.
  internal/core/openapi/application.go
  internal/core/openapi/context.go
  internal/core/openapi/dictionary.go
  internal/core/openapi/openapi.go
  internal/core/openapi/user.go
  internal/pkg/context/context.go
  pkg/entity/result/envcd_result.go
  pkg/entity/result/envcd_result_test.go
Labels: enhancement

#97 [type: refactor] refactor openapi and dictionary.
  internal/core/openapi/application.go
  internal/core/openapi/context.go
  internal/core/openapi/dictionary.go
  internal/core/openapi/openapi.go
  internal/core/openapi/user.go
Labels: enhancement

#98 [type: refactor] refactor jwt & result.failure.
  internal/core/jwt/authjwt.go
  internal/core/openapi/user.go
  internal/core/storage/dao/application.go
  internal/core/storage/dao/dictionary.go
  internal/core/storage/dao/logging.go
  internal/core/storage/dao/permission.go
  internal/core/storage/dao/user.go
  internal/pkg/config/conn_metadata.go
  pkg/entity/result/envcd_result.go
Labels: enhancement

#99 [type:refactor] refactor application to scopespace
  db/envcd.sql
  internal/core/configuration/configuration.go
  internal/core/openapi/dictionary.go
  internal/core/openapi/openapi.go
  internal/core/openapi/scopespace.go
  internal/core/storage/dao/scopespace.go
  internal/core/storage/xml/application_mapper.xml
  internal/core/storage/xml/dictionary_mapper.xml
  internal/core/storage/xml/scopespace_mapper.xml
  internal/pkg/constants/evncd_errors.go
  internal/pkg/entity/dictionary.go
  internal/pkg/entity/scopespace.go
Labels: enhancement

#100 [type: refactor] refactor openapi router group
  db/envcd.sql
  internal/core/openapi/dictionary.go
  internal/core/openapi/openapi.go
  internal/core/openapi/scopespace.go
  internal/core/openapi/user.go
Labels: enhancement

#101 [type: refactor] refactor permission action & add gin custom recovery.
  internal/core/openapi/dictionary.go
  internal/core/openapi/openapi.go
  internal/core/openapi/scopespace.go
  internal/core/openapi/user.go
  internal/core/plugin/permission/permission.go
  internal/pkg/context/context.go
Labels: enhancement

#104 [type: refactor] refactor errors
  internal/core/openapi/dictionary.go
  internal/core/plugin/logging/logging.go
  internal/core/plugin/permission/permission.go
  internal/pkg/plugin/sort.go
  pkg/entity/result/envcd_result.go
  pkg/entity/result/evncd_errors.go
Labels: enhancement

#105 refactor
  internal/core/openapi/dictionary.go
  internal/core/openapi/user.go
  internal/core/storage/dao/dao.go
Labels: enhancement

#106 update readme
  README.md
Labels: enhancement

#107 [type: refactor] refactor the envcd errors.
  README.md
  internal/core/openapi/dictionary.go
  internal/core/openapi/openapi.go
  internal/core/openapi/user.go
  internal/core/plugin/chain.go
  internal/core/plugin/chain_test.go
  pkg/entity/result/envcd_result.go
  pkg/entity/result/envcd_result_test.go
  pkg/entity/result/evncd_errors.go
Labels: enhancement

#113 update uri query params
  internal/core/openapi/openapi.go
Labels: enhancement, refactor, openapi

#115 [type: refactor] refactor dictionary and user logic.
  go.mod
  go.sum
  internal/core/openapi/dictionary.go
  internal/core/openapi/openapi.go
  internal/core/openapi/password.go
  internal/core/openapi/scopespace.go
  internal/core/openapi/user.go
Labels: enhancement, refactor, openapi

#116 [type:fix] fix db
  internal/core/openapi/dictionary.go
  internal/core/storage/xml/scopespace_mapper.xml
  internal/pkg/entity/scopespace.go
Labels: enhancement, openapi

#117 fix ddl
  db/envcd.sql
Labels: enhancement

#120 [type: refactor] refactor openapi,token & remove chain.
  internal/core/configuration/configuration.go
  internal/core/openapi/context.go
  internal/core/openapi/dictionary.go
  internal/core/openapi/openapi.go
  internal/core/openapi/scopespace.go
  internal/core/openapi/token.go
  internal/core/openapi/user.go
  internal/core/plugin/chain.go
  internal/core/plugin/chain_test.go
  internal/core/plugin/logging/logging.go
  internal/core/plugin/logging/logging_test.go
  internal/core/plugin/permission/permission.go
  internal/pkg/context/context.go
  internal/pkg/data/envcd_data.go
  internal/pkg/data/envcd_data_test.go
  internal/pkg/entity/user.go
  internal/pkg/executor/chain.go
  internal/pkg/executor/executor.go
  internal/pkg/plugin/plugin.go
  internal/pkg/plugin/sort.go
  internal/pkg/result/envcd_result.go
  internal/pkg/result/envcd_result_test.go
  internal/pkg/result/evncd_errors.go
  pkg/entity/user.go
Labels: documentation, refactor, openapi

#122 [type: refactor] refactor the token parser and validate logic.
  internal/core/openapi/context.go
  internal/core/openapi/token.go
  internal/core/openapi/user.go
  internal/pkg/context/context.go
Labels: enhancement, refactor, openapi

#124 code polish
  internal/core/openapi/context.go
  internal/core/openapi/openapi.go
  internal/core/openapi/token.go
  internal/core/openapi/user.go
Labels: enhancement, refactor
