Repository acmestack/envcd, pull requests merged in 2022-07, with the labels that each got.

#20 [type:feat] add core dictionary module.
  envcd/core/dictionary/.gitkeep
  envcd/core/dictionary/dictionary.go
  envcd/core/dictionary/dictionary_test.go
Labels: help wanted

#23 [type: feat] add parse yaml config file logic.
  cmd/envcd/main.go
  config/envcd.yaml
  envcd
  go.mod
  go.sum
  internal/envcd/envcd.go
  internal/pkg/config/config.go
  internal/pkg/config/config_properties.go
  internal/pkg/config/config_test.go
Labels: enhancement

#26 [type: refactor] refactor exchanger and chain
  internal/core/dictionary/dictionary.go
  internal/core/exchanger/etcd/etcd.go
  internal/core/exchanger/exchanager.go
  internal/core/exchanger/exchanager_test.go
  internal/core/storage/memory/memory.go
  internal/core/storage/mysql/.gitkeep
  internal/pkg/array/array.go
  internal/pkg/exchanger/chain.go
  internal/pkg/exchanger/exchanger.go
  internal/pkg/sync/sync.go
Labels: enhancement

#29 fix connect metadata & add some test
  internal/envcd/envcd.go
  internal/pkg/config/config.go
  internal/pkg/config/config_test.go
  internal/pkg/config/conn_metadata.go
  internal/pkg/config/conn_metadata_test.go
Labels: enhancement

#36 refactor exchanger bridge logic into envcd.
  cmd/envcd/main.go
  internal/core/exchanger/exchanager.go
  internal/core/openapi/openapi.go
  internal/envcd/envcd.go
  internal/envcd/envcd_test.go
Labels: enhancement

#38 [type: feat] add response data.
  internal/core/plugin/chain.go
  internal/core/plugin/response/data.go
  internal/core/plugin/response/data_test.go
  internal/envcd/envcd.go
  internal/envcd/envcd_test.go
Labels: enhancement

#39 [type: feat] add db script.
  db/envcd.sql
Labels: enhancement

#43 code polish & add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
  internal/core/plugin/chain.go
  internal/pkg/executor/chain.go
  internal/pkg/plugin/plugin.go
Labels: enhancement

#48 add context field.
  internal/core/openapi/openapi.go
  internal/core/plugin/chain.go
  internal/core/plugin/chain_test.go
  internal/core/plugin/logging/logging.go
  internal/core/plugin/permission/permission.go
  internal/core/plugin/response/response.go
  internal/pkg/context/context.go
  internal/pkg/executor/chain.go
  internal/pkg/executor/executor.go
Labels: enhancement

#49 [type: refactor] refactor executor & chain & envcd data.
  internal/core/configuration/configuration.go
  internal/core/openapi/openapi.go
  internal/core/plugin/chain.go
  internal/core/plugin/chain_test.go
  internal/core/plugin/logging/logging.go
  internal/core/plugin/permission/permission.go
  internal/core/plugin/response/response.go
  internal/pkg/context/context.go
  internal/pkg/executor/chain.go
  internal/pkg/executor/executor.go
  pkg/entity/data/envcd_data.go
  pkg/entity/data/envcd_data_test.go
  pkg/entity/data/envcd_result.go
  pkg/entity/data/envcd_result_test.go
  pkg/entity/envcd_data.go
Labels: enhancement

#33 [type:feat] add etcd exchanger client
  .github/workflows/go.yml
  go.mod
  go.sum
  internal/core/exchanger/etcd/etcd.go
  internal/core/exchanger/etcd/etcd_test.go
  internal/envcd/envcd.go
  internal/envcd/envcd_test.go
Labels: good first issue

#50 [type:fix] fix etcd config param
  internal/core/exchanger/etcd/etcd.go
  internal/core/exchanger/etcd/etcd_test.go
  internal/envcd/envcd.go
  internal/envcd/envcd_test.go
Labels: enhancement

#56 [type:refactor] refactor log
  internal/core/plugin/logging/logging.go
  internal/core/plugin/logging/logging_test.go
Labels: enhancement

#55 [type: refactor] remove response plugin
  internal/core/exchanger/etcd/etcd.go
  internal/core/openapi/openapi.go
  internal/core/plugin/chain.go
  internal/core/plugin/response/response.go
  internal/util/contextutil.go
Labels: enhancement

#59 update Architecture image
  README.md
  envcd.png
  envcd.svg
Labels: enhancement

#60 [type: refactor] refactor exchanger
  internal/core/exchanger/etcd/etcd.go
  internal/core/exchanger/etcd/etcd_test.go
  internal/core/openapi/admin_group.go
  internal/core/synccenter/websocket_sync.go
  internal/core/watch/.gitkeep
  internal/envcd/envcd.go
  internal/envcd/envcd_test.go
  internal/pkg/constants/constants.go
  internal/pkg/exchanger/exchanger.go
  internal/pkg/sync/sync.go
Labels: enhancement

#61 [type: refactor] optimize exchanger logic.
  cmd/envcd/main.go
  internal/core/exchanger/exchange.go
  internal/core/exchanger/exchange_test.go
  internal/core/openapi/admin_group.go
  internal/core/openapi/envcd_group.go
  internal/core/openapi/openapi.go
  internal/envcd/envcd.go
  internal/pkg/exchanger/exchanger.go
Labels: enhancement

#62 [type: refactor] refactor config.
  config/envcd.yaml
  internal/core/exchanger/etcd/etcd.go
  internal/core/exchanger/etcd/etcd_test.go
  internal/core/exchanger/exchange.go
  internal/core/exchanger/exchange_test.go
  internal/core/storage/storage.go
  internal/envcd/envcd.go
  internal/pkg/config/config.go
  internal/pkg/config/config_test.go
  internal/pkg/config/conn_metadata.go
  internal/pkg/config/conn_metadata_test.go
Labels: enhancement

#63 [type: refactor] optimize config
  config/envcd.yaml
  internal/core/exchanger/exchange.go
  internal/core/openapi/auth.go
  internal/core/openapi/dictionary.go
  internal/core/openapi/openapi.go
  internal/pkg/config/config.go
Labels: enhancement

#64 [type: bug] fix exchanger bug.
  config/envcd.yaml
  internal/core/exchanger/exchange.go
  internal/core/openapi/openapi.go
Labels: bug, enhancement

#65 [type: refactor] optimize interface value check logic.
  internal/core/exchanger/exchange.go
  internal/core/exchanger/exchange_test.go
Labels: enhancement

#67 [type: test] cover test
  internal/core/exchanger/etcd/etcd.go
  internal/core/exchanger/exchange_test.go
  internal/core/plugin/chain_test.go
  internal/pkg/config/config_test.go
Labels: enhancement

#68 [type: refactor] refactor db script.
  db/envcd.sql
Labels: enhancement

#71 chore: modify sql
  db/envcd.sql
Labels: enhancement

#72 Revert "chore: modify sql"
  db/envcd.sql
Labels: wontfix

#73 [type:feat] add openapi
  internal/core/openapi/auth.go
  internal/core/openapi/dictionary.go
  internal/core/openapi/openapi.go
Labels: enhancement

#74 [type:feat] add gobatis
  db/envcd.sql
  go.mod
  go.sum
  internal/core/configuration/configuration.go
  internal/core/openapi/auth.go
  internal/core/storage/dao/application_proxy.go
  internal/core/storage/dao/dictionary_proxy.go
  internal/core/storage/dao/logging_proxy.go
  internal/core/storage/dao/permission_proxy.go
  internal/core/storage/dao/user_proxy.go
  internal/core/storage/storage.go
  internal/core/storage/xml/application_mapper.xml
  internal/core/storage/xml/dictionary_mapper.xml
  internal/core/storage/xml/logging_mapper.xml
  internal/core/storage/xml/permission_mapper.xml
  internal/core/storage/xml/user_mapper.xml
  internal/pkg/entity/application.go
  internal/pkg/entity/base.go
  internal/pkg/entity/dictionary.go
  internal/pkg/entity/logging.go
  internal/pkg/entity/permission.go
  internal/pkg/entity/user.go
  pkg/entity/user.go
Labels: enhancement

#75 [type: refactor] refactor dao & storage.
  internal/core/openapi/auth.go
  internal/core/storage/dao/dao.go
  internal/core/storage/dao/user_proxy.go
  internal/core/storage/storage.go
Labels: enhancement
